### ISSUE TITLE
windows - run .sh

### ISSUE THREAD

**Issue by sircambridge** [maxim-saplin/flutter_python_starter#3]
this is a great project!! i am running something similar on windows with flutter managing a python process and talks to it via websockets and http, and i want to try this out.

can i ask a silly question - are we expected to run the .sh file on WSL in windows?

EDIT: nevermind I see we can install git bash windows.

**Comment by sircambridge** [comment]
EDIT: nevermind I see we can install git bash windows.

**Comment by maxim-saplin** [comment]
Great! Let me know how it works for you)
