### ISSUE TITLE
Failure while launching server process. It stopped right after starting. Exit code: 1

### ISSUE THREAD

**Issue by Malay1121** [maxim-saplin/flutter_python_starter#5]
I am getting this issue after creating a self-contained Python executable.

Failure while launching server process. It stopped right after starting. Exit code: 1

**Comment by maxim-saplin** [comment]
More detail Is needed

**Comment by Malay1121** [comment]
@maxim-saplin  Can you please explain what kind of details?
I am trying to run the example and getting an error in init_py_native.dart and init_py.dart files.
![image](https://github.com/maxim-saplin/flutter_python_starter/assets/56907997/e6d9b30d-675d-4c16-94ce-3bbc64842ed3)
![image](https://github.com/maxim-saplin/flutter_python_starter/assets/56907997/f1b0c1ac-17f9-4e0e-92b4-a3d08ba0e538)

Can we connect on Discord or somewhere?

**Comment by Malay1121** [comment]
@maxim-saplin

**Comment by maxim-saplin** [comment]
Try running the Python binary manually, I suspect there's sth wrong with the file produced by PyInstaller. You can also try running the python server file directly, i.e. `python server.py` and see if you get any errors there

**Comment by Malay1121** [comment]
> Try running the Python binary manually, I suspect there's sth wrong with the file produced by PyInstaller. You can also try running the python server file directly, i.e. `python server.py` and see if you get any errors there

Yes, that way it is working perfectly fine, but can't it automatically run as soon as the flutter app starts?

**Comment by maxim-saplin** [comment]
`assets/server_py_flutter_win.exe` works well?

Yes, it is supposed to be started automatically and apparently it is not starting, my suspect is that the binary might be failing.

**Comment by Malay1121** [comment]
> `assets/server_py_flutter_win.exe` works well?
> 
> Yes, it is supposed to be started automatically and apparently it is not starting, my suspect is that the binary might be failing.

Is there any way to fix it? Should I try generating exe by myself?

**Comment by maxim-saplin** [comment]
You can try running pyinstaller manually and see what it produces, maybe play with params you send into it

`python -m PyInstaller --onefile --noconfirm --clean --log-level=WARN --name="$exeNameFull" --paths="./grpc_generated" server.py`

**Comment by Malay1121** [comment]
> You can try running pyinstaller manually and see what it produces, maybe play with params you send into it
> 
> `python -m PyInstaller --onefile --noconfirm --clean --log-level=WARN --name="$exeNameFull" --paths="./grpc_generated" server.py`

It is still throwing the same error :(

**Comment by Malay1121** [comment]
@maxim-saplin I think it is an issue from Flutter side. When I try to run the .exe file, it starts the server. Flutter is not able to run it properly.

**Comment by maxim-saplin** [comment]
I still don't get if the binary from the assets runs fine

**Comment by Malay1121** [comment]
What are we gonna do now? I am trying to print the result after a Process has started or running to check for issues.

**Comment by Malay1121** [comment]
@maxim-saplin  Is this issue because of some missing permissions?

**Comment by Malay1121** [comment]
Hey @maxim-saplin , I fixed this issue by commenting ```shutdownPyIfAnyImpl()``` function. Is this of any importance?

**Comment by maxim-saplin** [comment]
There might be a bug... Try using `await` instead of commenting out:
```
await shutdownPyIfAnyImpl();
```

This method ensures there's no Python binary running before launching a new one

**Comment by Malay1121** [comment]
> There might be a bug... Try using `await` instead of commenting out:
> 
> ```
> await shutdownPyIfAnyImpl();
> ```
> 
> This method ensures there's no Python binary running before launching a new one

@maxim-saplin  Yep! It works after using await! Change it in the repository, other people might face this issue again. Thank you!

**Comment by maxim-saplin** [comment]
Thanks for reporting. Committed the fix
