### ISSUE TITLE
Working with USB devices via python

### ISSUE THREAD

**Issue by avdept** [maxim-saplin/flutter_python_starter#6]
So, this is not an issue, but rather question. Does python have access to connected USB devices? I'm mainly interested in desktop platforms. I have a python lib which does some USB device read/write ops and kinda wanted to bring it into standalone flutter desktop app.

**Comment by maxim-saplin** [comment]
Don't see why it wouldn't

**Comment by avdept** [comment]
> Don't see why it wouldn't

Ok, sounds good, thanks
